[graph]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[advisories]
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
    "MIT-0",
    "CDLA-Permissive-2.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
